#!/bin/bash
##
## example-array.slurm.sh: submit an array of jobs with a varying parameter
##
## Lines starting with #SBATCH are read by Slurm. Lines starting with ## are comments.
## All other lines are read by the shell.
##
##SBATCH --account=priority-stephanieewing        #specify the account to use
#SBATCH --job-name=bWT0215            # job name
#SBATCH --partition=unsafe              # queue partition to run the job in
#SBATCH --nodes=1                       # number of nodes to allocate
#SBATCH --ntasks-per-node=1             # number of descrete tasks - keep at one except for MPI
#SBATCH --cpus-per-task=2              # number of cores to allocate
#SBATCH --mem=250G                     # 2000 MB of Memory allocated; set --mem with care
#SBATCH --time=1-00:00:00                 # Maximum job run time
##SBATCH --array=1-3                  # Number of jobs in array
#SBATCH --output=example-%j.out
#SBATCH --error=example-%j.err
cd amazon_space/COA_6092/6092_sickle
bbnorm.sh -in1=WT_02_15_20230725_A2_6092_S9_L001_R1.sickle.fastq -in2=WT_02_15_20230725_A2_6092_S9_L001_R2.sickle.fastq \
-out1=WT_02_15_20230725_A2_6092_S9_L001_R1.bbnorm.fastq -out2=WT_02_15_20230725_A2_6092_S9_L001_R2.bbnorm.fastq target=100 min=5
