#!/bin/bash
##
## example-array.slurm.sh: submit an array of jobs with a varying parameter
##
## Lines starting with #SBATCH are read by Slurm. Lines starting with ## are comments.
## All other lines are read by the shell.
##
##SBATCH --account=priority-stephanieewing        #specify the account to use
#SBATCH --job-name=sample            # job name
#SBATCH --partition=unsafe              # queue partition to run the job in
#SBATCH --nodes=1                       # number of nodes to allocate
#SBATCH --ntasks-per-node=1             # number of descrete tasks - keep at one except for MPI
#SBATCH --cpus-per-task=2              # number of cores to allocate
#SBATCH --mem=50G                     # 2000 MB of Memory allocated; set --mem with care
#SBATCH --time=1-00:00:00                 # Maximum job run time
##SBATCH --array=1-3                  # Number of jobs in array
#SBATCH --output=example-%j.out
#SBATCH --error=example-%j.err

## Run 'man sbatch' for more information on the options above.
cd amazon_space/COA_6092/
sickle pe -f CN_07_30_20230718_H1_6092_S8_L001_R1_001.fastq.gz -r CN_07_30_20230718_H1_6092_S8_L001_R2_001.fastq.gz -t sanger \
 -o CN_07_30_20230718_H1_6092_S8_L001_R1.sickle.fastq -p CN_07_30_20230718_H1_6092_S8_L001_R2.sickle.fastq -s CN_07_30_20230718_H1_6092_singles.fastq 
